#!/bin/bash
# $1 -> sciezka do training.for
# $2 -> sciezka do training.eng
# $3 -> output folder align_for_eng
# $4 -> output folder align_eng_for
ln -sf $1 ./training.for
ln -sf $2 ./training.eng

# Ustawienie flagi executable
chmod +x ./plain2snt.out
chmod +x ./mkcls
chmod +x ./snt2cooc.out
chmod +x ./GIZA++

echo "GIZA++ etap 1/7: przygotowanie slownikow (PL i EN)..."
./plain2snt.out training.for training.eng

echo "GIZA++ etap 2/7: przygotowanie plikow klas (PL)..."
./mkcls -ptraining.for -Vtraining.for.vcb.classes -n2

echo "GIZA++ etap 3/7: przygotowanie plikow klas (EN)..."
./mkcls -ptraining.eng -Vtraining.eng.vcb.classes -n2

echo "GIZA++ etap 4/7 przygotowanie coocurrence file (PL -> EN)..."
./snt2cooc.out training.for.vcb training.eng.vcb training.for_training.eng.snt > cooc_for_eng.cooc

echo "GIZA++ etap 5/7 przygotowanie coocurrence file (EN -> PL)..."
./snt2cooc.out training.eng.vcb training.for.vcb training.eng_training.for.snt > cooc_eng_for.cooc

echo "GIZA++ etap 6/7 wyrownanie (PL -> EN)..."
./GIZA++ -S training.for.vcb -T training.eng.vcb -C training.for_training.eng.snt -CoocurrenceFile cooc_for_eng.cooc -o alignment -outputpath $3

echo "GIZA++ etap 7/7 wyrownanie (EN -> PL)..."
./GIZA++ -S training.eng.vcb -T training.for.vcb -C training.eng_training.for.snt -CoocurrenceFile cooc_eng_for.cooc -o alignment -outputpath $4